// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: version/v1/version.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_version_v1_version_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_version_v1_version_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_version_v1_version_proto_rawDescGZIP(), []int{0}
}

type GetVersionResponse struct {
	state          protoimpl.MessageState     `protogen:"open.v1"`
	CurrentVersion string                     `protobuf:"bytes,1,opt,name=currentVersion,proto3" json:"currentVersion,omitempty"`
	Update         *GetVersionResponse_Update `protobuf:"bytes,2,opt,name=update,proto3" json:"update,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_version_v1_version_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_version_v1_version_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_version_v1_version_proto_rawDescGZIP(), []int{1}
}

func (x *GetVersionResponse) GetCurrentVersion() string {
	if x != nil {
		return x.CurrentVersion
	}
	return ""
}

func (x *GetVersionResponse) GetUpdate() *GetVersionResponse_Update {
	if x != nil {
		return x.Update
	}
	return nil
}

type GetVersionResponse_Update struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse_Update) Reset() {
	*x = GetVersionResponse_Update{}
	mi := &file_version_v1_version_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse_Update) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse_Update) ProtoMessage() {}

func (x *GetVersionResponse_Update) ProtoReflect() protoreflect.Message {
	mi := &file_version_v1_version_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse_Update.ProtoReflect.Descriptor instead.
func (*GetVersionResponse_Update) Descriptor() ([]byte, []int) {
	return file_version_v1_version_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetVersionResponse_Update) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetVersionResponse_Update) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_version_v1_version_proto protoreflect.FileDescriptor

const file_version_v1_version_proto_rawDesc = "" +
	"\n" +
	"\x18version/v1/version.proto\x12\x05mr.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11GetVersionRequest\"\xb0\x01\n" +
	"\x12GetVersionResponse\x12&\n" +
	"\x0ecurrentVersion\x18\x01 \x01(\tR\x0ecurrentVersion\x128\n" +
	"\x06update\x18\x02 \x01(\v2 .mr.v1.GetVersionResponse.UpdateR\x06update\x1a8\n" +
	"\x06Update\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2o\n" +
	"\aVersion\x12d\n" +
	"\n" +
	"GetVersion\x12\x18.mr.v1.GetVersionRequest\x1a\x19.mr.v1.GetVersionResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/version/v1/GetVersionB$Z\"github.com/vlanse/glmr/proto/mr/v1b\x06proto3"

var (
	file_version_v1_version_proto_rawDescOnce sync.Once
	file_version_v1_version_proto_rawDescData []byte
)

func file_version_v1_version_proto_rawDescGZIP() []byte {
	file_version_v1_version_proto_rawDescOnce.Do(func() {
		file_version_v1_version_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_version_v1_version_proto_rawDesc), len(file_version_v1_version_proto_rawDesc)))
	})
	return file_version_v1_version_proto_rawDescData
}

var file_version_v1_version_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_version_v1_version_proto_goTypes = []any{
	(*GetVersionRequest)(nil),         // 0: mr.v1.GetVersionRequest
	(*GetVersionResponse)(nil),        // 1: mr.v1.GetVersionResponse
	(*GetVersionResponse_Update)(nil), // 2: mr.v1.GetVersionResponse.Update
}
var file_version_v1_version_proto_depIdxs = []int32{
	2, // 0: mr.v1.GetVersionResponse.update:type_name -> mr.v1.GetVersionResponse.Update
	0, // 1: mr.v1.Version.GetVersion:input_type -> mr.v1.GetVersionRequest
	1, // 2: mr.v1.Version.GetVersion:output_type -> mr.v1.GetVersionResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_version_v1_version_proto_init() }
func file_version_v1_version_proto_init() {
	if File_version_v1_version_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_version_v1_version_proto_rawDesc), len(file_version_v1_version_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_version_v1_version_proto_goTypes,
		DependencyIndexes: file_version_v1_version_proto_depIdxs,
		MessageInfos:      file_version_v1_version_proto_msgTypes,
	}.Build()
	File_version_v1_version_proto = out.File
	file_version_v1_version_proto_goTypes = nil
	file_version_v1_version_proto_depIdxs = nil
}
