// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: editor/v1/editor.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpenProjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     int64                  `protobuf:"varint,1,opt,name=projectId,proto3" json:"projectId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenProjectRequest) Reset() {
	*x = OpenProjectRequest{}
	mi := &file_editor_v1_editor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenProjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenProjectRequest) ProtoMessage() {}

func (x *OpenProjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_editor_v1_editor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenProjectRequest.ProtoReflect.Descriptor instead.
func (*OpenProjectRequest) Descriptor() ([]byte, []int) {
	return file_editor_v1_editor_proto_rawDescGZIP(), []int{0}
}

func (x *OpenProjectRequest) GetProjectId() int64 {
	if x != nil {
		return x.ProjectId
	}
	return 0
}

type OpenProjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OpenProjectResponse) Reset() {
	*x = OpenProjectResponse{}
	mi := &file_editor_v1_editor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OpenProjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpenProjectResponse) ProtoMessage() {}

func (x *OpenProjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_editor_v1_editor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpenProjectResponse.ProtoReflect.Descriptor instead.
func (*OpenProjectResponse) Descriptor() ([]byte, []int) {
	return file_editor_v1_editor_proto_rawDescGZIP(), []int{1}
}

var File_editor_v1_editor_proto protoreflect.FileDescriptor

const file_editor_v1_editor_proto_rawDesc = "" +
	"\n" +
	"\x16editor/v1/editor.proto\x12\x05mr.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\x12OpenProjectRequest\x12\x1c\n" +
	"\tprojectId\x18\x01 \x01(\x03R\tprojectId\"\x15\n" +
	"\x13OpenProjectResponse2q\n" +
	"\x06Editor\x12g\n" +
	"\vOpenProject\x12\x19.mr.v1.OpenProjectRequest\x1a\x1a.mr.v1.OpenProjectResponse\"!\x82\xd3\xe4\x93\x02\x1b:\x01*\"\x16/editor/v1/OpenProjectB(Z&github.com/vlanse/glmr/proto/editor/v1b\x06proto3"

var (
	file_editor_v1_editor_proto_rawDescOnce sync.Once
	file_editor_v1_editor_proto_rawDescData []byte
)

func file_editor_v1_editor_proto_rawDescGZIP() []byte {
	file_editor_v1_editor_proto_rawDescOnce.Do(func() {
		file_editor_v1_editor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_editor_v1_editor_proto_rawDesc), len(file_editor_v1_editor_proto_rawDesc)))
	})
	return file_editor_v1_editor_proto_rawDescData
}

var file_editor_v1_editor_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_editor_v1_editor_proto_goTypes = []any{
	(*OpenProjectRequest)(nil),  // 0: mr.v1.OpenProjectRequest
	(*OpenProjectResponse)(nil), // 1: mr.v1.OpenProjectResponse
}
var file_editor_v1_editor_proto_depIdxs = []int32{
	0, // 0: mr.v1.Editor.OpenProject:input_type -> mr.v1.OpenProjectRequest
	1, // 1: mr.v1.Editor.OpenProject:output_type -> mr.v1.OpenProjectResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_editor_v1_editor_proto_init() }
func file_editor_v1_editor_proto_init() {
	if File_editor_v1_editor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_editor_v1_editor_proto_rawDesc), len(file_editor_v1_editor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_editor_v1_editor_proto_goTypes,
		DependencyIndexes: file_editor_v1_editor_proto_depIdxs,
		MessageInfos:      file_editor_v1_editor_proto_msgTypes,
	}.Build()
	File_editor_v1_editor_proto = out.File
	file_editor_v1_editor_proto_goTypes = nil
	file_editor_v1_editor_proto_depIdxs = nil
}
